In [2]:
import torch

In [3]:
a = torch.tensor(5)#torch.tensor 在做什么？--->把数据变成张量
a.shape

torch.Size([])

In [4]:
b = torch.tensor([1,2,3])
b.shape

torch.Size([3])

In [9]:
c = torch.tensor([[1,2,3],
                  [4,5,6]])
c.shape

torch.Size([2, 3])

In [13]:
d = torch.randn(2,3,4)#生成2张表，每张表都是3行4列的张量
d

tensor([[[-2.4498,  0.6758, -0.6637, -0.5336],
         [-0.2639, -1.6367,  0.7393,  0.6088],
         [-0.5445, -0.2619, -0.6851, -1.0154]],

        [[-0.4909,  0.5038, -1.7090, -0.3978],
         [ 1.2087,  0.0851, -0.3539,  0.3279],
         [ 1.4694, -0.9632, -0.4450, -0.8226]]])

In [25]:
d = torch.randn(2,3,4)
d[:,0,:] #两张表的第1行
d[:,2,:].shape

torch.Size([2, 4])

In [27]:
x = torch.arange(12)
x.shape

torch.Size([12])

In [35]:
y = x.reshape(2,6)
y

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [37]:
y = x.view(2,2,3)
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [47]:
#广播 从右往左看,满足两个条件即可广播：
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([10,20,30])#和randn搞混了，认为是生成10个表，每个表20行30列

a+b

tensor([[11, 22, 33],
        [14, 25, 36]])

In [46]:
c = torch.randn(2,3)
d = torch.randn(3)

c + d #广播规则：从右到左广播，c+d时d的3-->1，3

tensor([[1.9662, 1.8723, 2.0871],
        [0.9836, 2.6144, 3.0546]])

In [63]:
m = torch.randn(3,4)#可以理解为3个列表，每个列表里有4个数
n = torch.randn(4)#1个列表，4个数

m,n

(tensor([[-0.6371,  0.5859,  0.6346, -0.5875],
         [-0.9663, -0.3489, -1.9508, -0.9656],
         [-0.7583,  1.6015, -0.4178,  0.0532]]),
 tensor([ 0.1823, -2.4913,  2.4630, -0.1052]))

In [73]:
#易混淆,
print(torch.randn(4).shape)  # shape: (4,)一维，一个方括号，"一行数"
print(torch.randn(1,4).shape)# shape: (1,4)二维，两个方括号，"一张只有1行的表"
print(torch.randn(4))
print(torch.randn(1,4))

torch.Size([4])
torch.Size([1, 4])
tensor([ 1.7738, -0.6588,  0.7904, -4.3274])
tensor([[ 1.2806, -0.5774,  0.0247,  1.4682]])


In [75]:
x = torch.randn(1,3)
w = torch.randn(5,3)

out = x @ w.T
out

tensor([[-3.3843,  3.6323, -0.5112, -2.4482,  0.0153]])

In [80]:
a = torch.randn(2,3,4)
b = torch.randn(2,4,5)

c = a @ b
c.shape

torch.Size([2, 3, 5])

In [83]:
a = torch.randn(2,1,3)
b = torch.randn(1,4,1)
(a+b).shape

torch.Size([2, 4, 3])

In [3]:
#神经网络中会用到大量的数学运算，而列表的加减乘除和张量的有很大不同，我们需要实际的数学运算
a = [1,2,3]
b = torch.tensor([1,2,3])
print(type(a))
print(type(b))

print(' ')

print(a + [2])
print(b + torch.tensor(2))

print(' ')

print(a * 2)
print(b * 2)

<class 'list'>
<class 'torch.Tensor'>
 
[1, 2, 3, 2]
tensor([3, 4, 5])
 
[1, 2, 3, 1, 2, 3]
tensor([2, 4, 6])


In [4]:
#且list没有维度/张量的概念
X = [[1,2],[3,4]]
#X.shape 报错
torch.tensor(X).shape

torch.Size([2, 2])

In [5]:
X = [[1,2],[3,4]]
X.shape 

AttributeError: 'list' object has no attribute 'shape'

In [14]:
#.item()只能对tensor张量使用，并且只读取一个数字，因为数字一多他不知道读谁
x = torch.randn(1)
x.item()

1.2890644073486328

In [ ]:
for x,y in zip(Xtr[:16],Ytr[:16]):
#等价于--------------------->
for i in range(16):
    x,y = Xtr[i],Ytr[i]

In [25]:
#zip练习
name = ['Andrej','karpathy']
scores = [100,95]
for x,y in zip(name,scores):
    print(x,'gets',y)

Andrej gets 100
karpathy gets 95
